INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1111, 'el rey leon', 6);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (2222, 'la sirenita', 6);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (3333, 'blanca nieves', 6);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (4444, 'crespusculo', 18);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (5555, 'donde estan las rubias', 16);
INSERT INTO cine.peliculas  (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (6666, 'malefica', 12);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (7777, 'pinocho', 6);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (8888, 'los juegos del hambre', 16);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (9999, 'una aventura extraordinaria', 13);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1222, 'up', 6);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1333, 'cinderella', 9);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1444, 'mulan', 6);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1555, 'madasacar', 6);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1666, 'las cronicas de narnia', 13);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1777, 'maze runner', 12);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1888, 'la princesa y el sapo', 6);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (1999, 'los vengadores', 6);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (2111, 'aquaman', 16);
INSERT INTO cine.peliculas (`p_codigo`, `nombre`, `calificacionEdad`) VALUES (2333, 'divergente', 12);
INSERT INTO cine.peliculas(`p_codigo`, `nombre`, `calificacionEdad`) VALUES (2444, 'insurgente', 12);